# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': '模型', 'verbose_name_plural': '模型'},
        ),
        migrations.AlterModelOptions(
            name='sensors',
            options={'verbose_name': '传感器', 'verbose_name_plural': '传感器'},
        ),
        migrations.AlterField(
            model_name='models',
            name='description',
            field=models.CharField(max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='models',
            name='height',
            field=models.CharField(max_length=30, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='models',
            name='latitude',
            field=models.CharField(max_length=30, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='models',
            name='longitude',
            field=models.CharField(max_length=30, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='models',
            name='modelName',
            field=models.CharField(max_length=20, unique=True, verbose_name='模型名'),
        ),
        migrations.AlterField(
            model_name='models',
            name='modelUrl',
            field=models.CharField(max_length=45, verbose_name='模型存储路径'),
        ),
        migrations.AlterField(
            model_name='models',
            name='scale',
            field=models.CharField(max_length=10, verbose_name='模型比例'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='height',
            field=models.CharField(max_length=30, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='holesNum',
            field=models.IntegerField(default=0, verbose_name='测孔数'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='latitude',
            field=models.CharField(max_length=30, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='longitude',
            field=models.CharField(max_length=30, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='modelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildings.Models', verbose_name='模型名'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='sensorId',
            field=models.IntegerField(default=0, verbose_name='传感器编号'),
        ),
    ]
