# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0003_auto_20180606_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildings.Models', verbose_name='模型名')),
            ],
            options={
                'verbose_name_plural': '测试',
                'verbose_name': '测试',
            },
        ),
    ]
