# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0005_auto_20180606_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.CharField(max_length=45, verbose_name='东')),
                ('south', models.CharField(max_length=45, verbose_name='南')),
                ('west', models.CharField(max_length=45, verbose_name='西')),
                ('north', models.CharField(max_length=45, verbose_name='北')),
                ('maxHeight', models.CharField(max_length=45)),
                ('minHeight', models.CharField(max_length=45)),
                ('serialNum', models.IntegerField(default=1, verbose_name='色块序号')),
                ('modelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildings.Models', verbose_name='模型名')),
                ('sensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildings.Sensors', verbose_name='传感器编号')),
            ],
            options={
                'verbose_name_plural': '色块',
                'verbose_name': '色块',
            },
        ),
    ]
