# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0006_holes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holes',
            options={},
        ),
    ]
