# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0007_auto_20180606_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holes',
            options={'verbose_name': '色块', 'verbose_name_plural': '色块'},
        ),
    ]
