# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildings', '0010_auto_20180607_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='internal',
            field=models.FloatField(default=0, verbose_name='测孔间距'),
        ),
    ]
